240813 pre deploy test
DEFRA/ado-pipeline-common pull request #52
Opened 2024-01-09 17:17 UTC by rajeshkaremane

# **What this PR does / why we need it**:
*A brief description of changes being made*
*Link to the relevant work items: e.g: Relates to ADO Work Item AB#213700 and builds on #3376 (link to ADO Build ID URL)*

# **Special notes for your reviewer**
*Any specific actions or notes on review?*

# Testing
*Any relevant testing information and pipeline runs.*

# Checklist (please delete before completing or setting auto-complete)
- [ ] Story Work items associated (not Tasks)
- [ ] Successful testing run(s) link provided
- [ ] Title pattern should be `{work item number}: {title}`
- [ ] Description covers all the changes in the PR
- [ ] This PR contains documentation
- [ ] This PR contains tests

# **How does this PR make you feel**:
![gif]([https://giphy.com/)

2024-01-12 17:37 UTC, DaRoszko requested changes

2024-01-12 17:37 UTC, DaRoszko commented on docs/AppBuildAndDeploy.md
> +        task: accessibility-test-pa11y
remove pally

2024-01-15 09:55 UTC, kbabigumira approved these changes

2024-01-15 09:58 UTC, rajeshkaremane commented on docs/AppBuildAndDeploy.md
> +        task: accessibility-test-pa11y
Removed pa11y

2024-01-15 10:01 UTC, kbabigumira approved these changes

2024-01-15 10:04 UTC, ganeshg2491 approved these changes

2024-01-15 10:24 UTC, DaRoszko approved these changes

2024-01-15 10:43 UTC, merged